### PR TITLE
Adds Nova 4.x Support

### LINKED ISSUE #128: Support Nova 4[Feature Request]
Now that Nova 4 is out, it would be great if we could update this package to support it. Let me know if you need any help with this and I may be able to dedicate some time to it.

### PR DESCRIPTION
**Pull request by dmason30**
This adds Nova 4.0 only support and has breaking changes and would, therefore, be a major release. 

- [x] Upgraded to Nova 4.x (Nova 3 support removed) 👋 
- [x] Upgraded Vue Chart.js to 4.x (Vue 3 compatibility) which forces update Chart.js 3.x
- [x] Upgraded to Chart.js 3.x (Chart.js 2 support removed) 👋 
- [x] Supports Nova 4 Light/Dark/System toggle 🌑 🌞 
- [x] Supports Nova 4 brand colour 🖌️ (only on charts using models) 🟥 🟦 🟩 
- [x] `YTD`, `QTD` and `MTD` filters have been changed to perform the same query as Trends & Metrics in Nova 4.x 🔍 
- [x] Charts using the built-in model data api will now show the classic Nova loading indicator when it is fetching data ⏲️ 

Closes #128 

I have kept all the package specific options the same, however, with the Chart.js update some will likely have to tweak their chart options as needed and follow this guide:

https://www.chartjs.org/docs/latest/getting-started/v3-migration.html

<details>
<summary>Click here for demo video</summary>
<video src="https://user-images.githubusercontent.com/20278756/165290451-89b6685b-dd77-4ad8-9b70-a7c632409ad9.mp4" />
</details>

### CODE REVIEW

**Comment by trovster** [comment]
You've updated to Chart.js 3.x but the codebase is based around v2 configuration, example `this.card.options.scales?.xAxes || {}`

**Comment by dmason30** [comment]
Yes but i changed the mapping so it works with Chart.js 3 perfectly fine. Doing it this way avoids the barrier of entry to this update. But it would be the package maintainers choice if they would want to change that as you would also need to update all the documentation to. 

The way I have done it avoids all that and I only had limited time to work on it!

**Comment by trovster** [comment]
Yeah, I understand the choice. Alas, it has broken something. The example of the bar chart with multiple columns per label is always stacked! I spent hours trying to get it unstacked.

**Comment by dmason30** [comment]
@trovster Sorry about that, this has been fixed in last commit 🚀

**Comment by trovster** [comment]
Ah! Superb dude. I didn’t realise you added the stacked or spread options compared to original codebase, I only investigated yours. The latest change - fixing stacked and reordering the spread is brilliant. Thanks for this. 👍

**Comment by GytisKr** [comment]
Hello, when do plan to realease this pull request?

**Comment by novelnet** [comment]
Any update?

**Comment by coroo** [comment]
Big thankyou @dmason30 for the PR to support the nova 4.x. I put the release at https://github.com/coroo/nova-chartjs/tree/v0.4.0.

**Pull request merged**
