### PR TITLE
:wrench: fix error for psql database connection

### PR DESCRIPTION
**Pull request by coroo**
Fix error for #52 Error work in Postgresql

### CODE REVIEW

**Comment by alberto-bottarini** [comment]
Using env("DB_CONNECTION") is not safe.

I could have more db connections. You should use query https://laravel.com/api/5.8/Illuminate/Database/Query/Builder.html#method_getConnection

**Comment by coroo** [comment]
Hi @alberto-bottarini , thankyou for your input.
But can you explain more which code that I need to use ?

**Comment by alberto-bottarini** [comment]
You could do, for example:

```
$model->getConnection()->getDriverName()
```

**Comment by coroo** [comment]
Thank you for your review @alberto-bottarini

**Pull request merged**
